# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: LoksimDetailDoku.tex
          working_directory: DetailDoku
      - name: Archive LoksimDetailDokup.pdf artifact
        uses: actions/upload-artifact@v2
        with:
          name: LoksimDetailDoku
          path: DetailDoku/LoksimDetailDoku.pdf
